dpla/KriKri

app/models/krikri/original_record.rb, spec/models/original_record_spec.rb
Marmotta assigns file extensions based on content type. The octet stream MIME Type causes OriginalRecords to have the `.bin` extension. This changes the default MIME to `text/xml` so the default extension will be `.xml`.
Note that Marmotta infers that `application/xml`, `text/plain`, and some other types are RDF Sources.
An unrelated minor fix I spotted while working on this is included as a separate commit.  I can rebase this into another branch/PR if desired.
=> Change default MIME Type for Original Records

lib/krikri/ldp/resource.rb, spec/ldp/resource_spec.rb
Connection Refused errors on LDP requests were being caught as ClientErrors, but do not have a `#response`, so were throwing no method on `nil` errors instead of something informative. This ensures that a useful error is always thrown.
I ran into this problem when messing around with `heidrun`.  I wrote a quick patch, and a test.  Maybe the test is a bit naive, since it relies on no activity on port 9999 on the host machine.  I couldn't find a way to get WebMock to mimic Connection Refused (with fairly minimal searching, I admit).
=> Ldp connection refused

spec/lib/krikri/harvesters/oai_harvester_spec.rb
This should clear up errors related to our having upgraded Faraday.
=> Remove Faraday User-Agent headers from mocks

db/migrate/20150106164218_add_opts_to_krikri_harvest_sources.rb, lib/krikri/harvester.rb, lib/krikri/harvesters/oai_harvester.rb, lib/krikri/software_agent.rb, spec/factories/krikri_activities.rb, spec/factories/krikri_harvest_sources.rb, spec/lib/krikri/harvesters/oai_harvester_spec.rb, spec/lib/krikri/software_agent_spec.rb
This adds an `opts` field to `HarvestSource` for storing serialized options that get passed to the harvester.  For example, a list of sets for an OAI harvester.
`Krikri::Harvester.expected_opts` has been added to help client code know what options to get from the user to store in `HarvestSource`.  See the comment below for that method.
OAIHarvester has also been changed to take 'uri' as an option instead of 'endpoint', to bring it inline with the HarvestSource model, which has a 'uri' field, not an 'endoint' field.
The next step, assuming this goes over well, is to make an Event that can read the `opts` in a HarvestSource and determine the right strategy for enqueueing jobs for the relevant harvester, e.g. do one harvest job for the whole harvest, or iterate over sets, using the same URI …
=> Add discovery of Harvester options

krikri.gemspec, solr_conf/schema.xml, spec/lib/krikri/mapper_spec.rb, spec/lib/krikri/mapping_dsl_spec.rb, spec/support/shared_examples/enrichment.rb
Updates the solr schema, makes some changes to property access in tests.
More importantly, pins this version tightly to `pre.7`. Previous `pre` versions of MAP haven't been compatible when updating, so it seems like a good idea to be pessimistic until we can release 4.0.0.0.
=> Update DPLA MAP dependency to pre.7

lib/krikri/harvesters/oai_harvester.rb, spec/factories/krikri_original_record.rb, spec/lib/krikri/harvesters/oai_harvester_spec.rb, spec/support/shared_examples/harvester.rb
Ensures that OAI `#records` and `#get_record` return the same result (content) for a given identifier.
Unfortunately, `OAI:Record` hides its raw XML, so it is necessary to rebuild the record from its parts.  The alternative is to monkeypatch an `element` attribute.
```ruby
class OAI::Record
attr_reader :element
def initialize(element)
@element = element
@status = get_attribute(element, 'status')
@identifier = xpath(element, './/identifier')
@datestamp = xpath(element, './/datestamp')
@set_spec = xpath_all(element, './/setSpec')
end
end
```
https://github.com/code4lib/ruby-oai/blob/master/lib/oai/client/record.rb
This ignores OAI provenance content from `<about>...</about>`.
=> Normalize OAI output

lib/krikri/mapper.rb, lib/krikri/registry.rb, spec/lib/krikri/registry_spec.rb
Add #register! in addition to existing #register
This accompanies a forthcoming PR in Heidrun that will allow Heidrun Resque workers to be started.
=> Allow Registry to force-register items

krikri.gemspec, lib/generators/krikri/install_generator.rb
jettywrapper 2.0.0 was released today. Krikri's gemspec did not require a
specific version, but the generators were locking it to ~> 1.8.3, which
led to a version conflict.
=> Update jettywrapper and lock to ~> 2.0

lib/krikri.rb, lib/krikri/harvester.rb, lib/krikri/harvesters/oai_harvester.rb, lib/krikri/md5_minter.rb, spec/lib/krikri/harvester_spec.rb, spec/lib/krikri/md5_minter_spec.rb, spec/support/shared_examples/harvester.rb
Submitting this for discussion.
Interested in ideas about more robust testing of edge cases for existing ID's. This needs to be able to replicate https://github.com/dpla/ingestion/blob/develop/lib/akamod/select-id.py#L55
=> Add legacy MD5 Minter

lib/krikri.rb, lib/krikri/parsers/qdc_parser.rb, spec/factories/krikri_original_record.rb, spec/lib/krikri/parsers/qdc_parser_spec.rb
Adds a qualified Dublin Core parser. The default root node path is the
one used by CONTENTdm. This can be overridden (like all Krikri::XmlParsers)
at the time of instantiation.
=> Add Krikri::Parsers::QdcParser

Guardfile
Fixes 'Guard::RSpec error: No cmd option specified, unable to run specs' error (see
http://stackoverflow.com/questions/25034530).
=> Fixup Guardfile to use new guard-rspec syntax

lib/krikri/mapping_dsl.rb, lib/krikri/mapping_dsl/child_declaration.rb, lib/krikri/mapping_dsl/parser_methods.rb, lib/krikri/mapping_dsl/rdf_subjects.rb, lib/krikri/parser.rb, lib/krikri/parsers/json_parser.rb, lib/krikri/parsers/xml_parser.rb, spec/lib/krikri/mapper_spec.rb, spec/lib/krikri/mapping_dsl/child_declaration_spec.rb, spec/lib/krikri/mapping_dsl/parser_methods_spec.rb, spec/lib/krikri/mapping_dsl/rdf_subjects_spec.rb, spec/lib/krikri/parser_value_array_spec.rb, spec/support/shared_examples/parser.rb
Adds functionality to the mapping DSL for creating instances of a resource class from each of a given parser node's values and for accessing parsed values in a more human readable fashion.
Creates a `RecordProxy` in the mapping DSL context. The special DSL method `#record` now returns an instance of this class.  The class accepts a call chain, with method names, their arguments (and blocks to pass through) which will be called against the parsed record (via `ValueArray`) when the record is processed.  `RecordProxy` mimics `Proc` in that it has `#call` and `#arity` methods.  This allows the rest of the DSL's interface to stay the same.
Adds a `ValueArray`, which encapsulates common access patterns for parsed record nodes.  `ValueArray`'s methods return instances of itself, as they intended …
=> DSL Methods & Resources

krikri.gemspec, lib/krikri/harvesters/couchdb_harvester.rb, spec/lib/krikri/harvesters/couchdb_harvester_spec.rb
The prerelease of Analysand fixes a bug I reported where document IDs were
not getting escaped properly (yipdw/analysand#7). We don't need to call
a view request and can instead use `Analysand:Database#get!`.
Also fixes one of the CouchdbHarvester specs for `#get_record`, which was
not implemented properly.
=> Simplify CouchdbHarvester#get_record

Rakefile, lib/generators/krikri/install_generator.rb, lib/tasks/jetty.rake
* Install Jetty configuration when running generator
* MARMOTTA_HOME:
* Use `#{app_root}/jetty/marmotta` by default instead of `#{app_root)/marmotta`
* Set MARMOTTA_HOME when running rake ci
=> Install Jetty config using generator; tweak MARMOTTA_HOME

lib/krikri/field_enrichment.rb, spec/support/shared_examples/enrichment.rb
Given a field chain like `{ :sourceResource => { :creator => :label } }`, values of `creator` that don't have a property `label` would previously cause the enrichment to fail.  Now they are simply passed over.
=> Skip unavailiable fields in FieldEnrichment

krikri.gemspec
Analysand 4.0.0 (officially released) fixes the workaround which introduced the
dependency on our prerelease for 1268f3b2a509b2cba0364d243722680733b9b0a7.
=> Change dependency from dpla-analysand to analysand

lib/krikri/provenance_query_client.rb
SPARQL queries were routing through an incomplete RDF::Marmotta implementation. That implementation currently makes a lot of very broad queries (i.e. `CONSTRUCT :s, :p, :o`), which really ought to be avoided.
=> Avoids the rdf-marmotta Repository for SPARQL

lib/krikri/ldp/resource.rb, spec/ldp/resource_spec.rb
This will retry the errors we have been seeing a maximum of four times, starting with a 0.025-0.0375 second delay, and doubling that interval for each retry.  The longest delay would be 0.2-0.3 seconds.
=> Retry LDP requests on certain Errors

krikri.gemspec, lib/krikri/engine.rb, lib/krikri/enrichments/parse_date.rb, lib/krikri/enrichments/timespan_split.rb, lib/krikri/util/extended_date_parser.rb, spec/lib/krikri/enrichments/parse_date_spec.rb, spec/lib/krikri/enrichments/timespan_split_spec.rb, spec/lib/krikri/util/extended_date_parser_spec.rb
Implements two date enrichments:
- `ParseDate` converts string values in individual fields to `Date` objects.  This enrichment is meant to be run on TimeSpan attributes `#begin`/`#end` when they have been mapped directly.
- `TimespanSplit` accepts a string value or a TimeSpan, and returns a timespan object with a single `#begin` and `#end`, if any can be found.  If no `#begin` and `#end` are set, they are parsed from `#providedLabel`.
Both rely on `Krikri::Util::ExtendedDateParser`, which parses strings to one of `Date`, `EDTF::Interval`, or `EDTF::Epoch`.  The last two represent date ranges; when they are returned to `TimespanSplit` it uses their methods to determine the start and end of the range.
=> Date Enrichments

spec/factories/krikri_original_record.rb
Builds were failing on dpla/KriKri#86, @AudreyAltman's compare records PR. Looking at [Travis logs](https://travis-ci.org/dpla/KriKri/builds/49515202#L755) for the failed build, running the database migrations (called by the Devise-related generator steps) were failing, because of a `NoMethodError` for `String#strip_heredoc`. This change introduces the minimal dependency on the specific ActiveSupport core extensions module used in the OriginalRecord factories.
=> Require ActiveSupport core_ext for Strings in OriginalRecord factories

README.md, app/controllers/krikri/records_controller.rb, app/controllers/krikri/validation_reports_controller.rb, app/models/krikri/original_record.rb, app/models/krikri/search_index_document.rb, app/views/krikri/records/show.html.erb, lib/krikri/engine.rb, lib/krikri/index_service.rb, lib/krikri/search_results_helper_behavior.rb, lib/tasks/krikri.rake, solr_conf/schema.xml, spec/helpers/krikri/records_helper_spec.rb, spec/lib/krikri/index_service_spec.rb, spec/models/dpla/map/aggregation_spec.rb, spec/models/original_record_spec.rb, spec/models/search_index_document_spec.rb
View original record and enhanced record side-by-side
* SearchIndexDocument model (subclass of SolrDocument) allows a single document returned from a Solr query to be associated with its DPLA::MAP::Aggregation
* New initializer mix-in to DPLA::MAP::Aggregation allows aggregation to be associated with its original record
* Allows OriginalRecord to be loaded from an identifier with a mime type extension
* Rake tasks save sample aggregations and original records to Marmotta
* New records#show view with helper methods in SearchResultsHelperBehavior
* IndexService does not attempt to index fields that are not defined in the Solr schema
To test in browser:
* Generate test app with engine cart
* You may need to `stop`, `clean`, and `config` jetty
* Follow new instructions in `README.md` to save …
=> Compare records

lib/krikri/mapper.rb, lib/krikri/mapping.rb, lib/krikri/parser.rb, spec/lib/krikri/mapper_spec.rb, spec/lib/krikri/mapping_spec.rb, spec/support/shared_examples/parser.rb
Krikri::Mapper::Agent receives only unparsed records, assuming that the
Mapping will handle parsing through `#process_record`.  The parser to
use is specified through the mapping definition with the `:parser`
option.
Previously, there was no way to pass arguments to the parser. Arguments
are not needed in most cases, but necessary for some `Krikri::XmlParser`
subclasses.  This adds `:parser_args`, allowing you to pass an array
of parser arguments when defining a mapping.
Krikri::Mapper.define(:scdl_qdc,
:parser => Krikri::QdcParser,
:parser_args => ['//qdc:qualifieddc']) do
...
end
=> Add parser arguments to mapping definitions

app/models/krikri/activity.rb, lib/krikri/harvester.rb, spec/lib/krikri/harvester_spec.rb, spec/models/activity_spec.rb
~~I'm submitting this mostly for input.  @markbreedlove: thoughts?~~
Now with more complete error handling; more or less as discussed at https://dpla.slack.com/archives/tech/p1423166676000192.
- Catches errors on individual records during `Harvester` runs, logging and passing over failed records.
- Adds logging to `Activity#run`. Failed jobs are logged, the error is rethrown and the `end_time` is set for both successes and failures. Sets `end_time` to `nil` when a "ended" job restarts, so `end_time` should never be earlier than `start_time`.
=> Add error logging to Harvester

lib/krikri/mapper.rb, lib/krikri/mapping_dsl/rdf_subjects.rb, spec/lib/krikri/mapper_agent_spec.rb, spec/lib/krikri/mapper_spec.rb, spec/lib/krikri/mapping_dsl/rdf_subjects_spec.rb
Adds error handling and logging for `Mapper` activities. These are handled similarly to `Harvester` error handling, this passes over failures on mapped records and logs the error message.
A separate commit addresses cases where empty value sets are passed to URI in the DSL.
=> Mapper error logging & empty DSL URI

Rakefile, lib/tasks/jetty.rake
* `rake ci` now invokes `engine_cart:clean` before running `engine_cart:generate`,
to allow for improved local testing by developers before pushing up their commits.
* Adds new `jetty:clean_marmotta_home` task, which deletes `MARMOTTA_HOME` if defined
to something other than the default. If `MARMOTTA_HOME` is set to the default, it will
automatically get removed by `jetty:clean`.
* Makes `jetty:clean_marmotta_home` a prerequsite for `jetty:clean`. This also removes a
second (accidental) invokation of `jetty:clean` from the previous tasks file.
* <strike>Adds a dependency on `rubyzip`, now required by Jettywrapper >= 2.0.1. Declaring
`rubyzip` as a development dependency was not adequate for some reason</strike> **Fixed by Jettywrapper >= 2.0.2**
=> Streamline and improve Rake tasks

lib/krikri/parser.rb, spec/lib/krikri/parser_value_array_spec.rb
Creates `ValueArray#fields` which accepts multiple fields/chains and gives their union.
Also adds:
- `ValueArray#[]=` with type checking
- `ValueArray#<<` with type checking
- `ValueArray#flatten` to return a new `ValueArray`
- `ValueArray#concat` to return a new `ValueArray`
=> Add ability select multiple fields from ValueArray

lib/krikri.rb, lib/krikri/mapping_dsl/parser_methods.rb, lib/krikri/parsers/oai_dc_parser.rb, lib/krikri/parsers/oai_parser_headers.rb, spec/lib/krikri/mapping_dsl/parser_methods_spec.rb, spec/lib/krikri/parsers/oai_dc_parser_spec.rb, spec/support/shared_examples/oai_parser_headers.rb
Adds a mixin module `OaiParserHeaders` for use with `XmlParser` classes.  This module adds a `#header` method which gives access to the `<oai:header>` tag and its members, even when that tag is out of scope of the root node.
Adds a specialized method to the mapping DSL via `ParserMethods` to access the header.  This method raises an error if no header exists.
=> Add `#header` node to OAI Parsers (and DSL method)

lib/krikri/mapper.rb, spec/lib/krikri/mapper_spec.rb
This tries to make `Mapper#map` a little more resilient and print prettier messages.
If it has been given actual records, the typical case, it will log a message that starts with something like this:
```
[3] pry(main)> puts Krikri::Mapper.map(:scdl_qdc, r).first.dump :ttl
Error processing mapping.
content: <?xml version="1.0"?>
<record xmlns="http://www.openarchives.org/OAI/2.0/">
<header>
[ ... ]
```
... with a newline-delimited stacktrace, like this:
```
scdl_qdc is not registered.
/home/dpla/krikri/lib/krikri/registry.rb:25:in `get'
/home/dpla/krikri/lib/krikri/mapper.rb:63:in `block in map'
/home/dpla/krikri/lib/krikri/mapper.rb:61:in `map'
/home/dpla/krikri/lib/krikri/mapper.rb:61:in `map'
(pry):3:in `<main>'
/home/dpla/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/pry-0.10.1/lib/pry …
```
=> Make Mapper#map's exception handling more robust

app/views/krikri/records/show.html.erb, lib/krikri/random_record_generator.rb, lib/krikri/search_results_helper_behavior.rb
This adds the ability to view a random record to the QA interface.  A record is randomly selected from Solr and displayed in the `records#show` view.  
To test in your browser window:
1. Generate test app and start jetty.
2. Index a sample record:
```bash
cd spec/internal
bundle exec rake krikri:samples:save_record
```
3. If you want to test the random selection, index more sample records, from the rails console:
```ruby
include FactoryGirl::Syntax::Methods
require 'dpla/map/factories'
agg = build(:aggregation)
agg.mint_id!('sample2')
graph = agg.to_jsonld['@graph'].first
Krikri::IndexService.add graph.to_json
Krikri::IndexService.commit
```
4. Start the rails server and open [http://localhost:3000/krikri/records/http:%2F%2Flocalhost:8983%2Fmarmotta%2Fldp%2Fitems%2Fkrikri_sample](http://lo …
=> Random record generator

lib/krikri/harvesters/oai_harvester.rb, spec/lib/krikri/harvesters/oai_harvester_spec.rb
- Adds `OAIHarvester#sets` to list sets.
- Adds ability to specify multiple sets to harvest by passing a list to the `:set` option on `#records` and `#record_ids`.
- Adds ability to blacklist sets in `#records` and `#record_ids` requests.
=> Add set access, multiple harvests and blacklisting to OAIHarvester

db/migrate/20150309160112_change_opts_in_krikri_activities.rb, spec/factories/krikri_activities.rb, spec/models/activity_spec.rb
Embiggens the `:opts` JSON blob used to pass options, to ensure cromulent option
storage and behavior for `Krikri::Activity` objects.
=> Add migration to change Krikri::Activity.opts from :string to :text

lib/krikri/harvesters/oai_harvester.rb, spec/lib/krikri/harvesters/oai_harvester_spec.rb
OAI harvests were sending their initial request for each set of options when the `#records` or `#record_ids` method was called. This meant that multiset harvests took a long time to start and were at risk of having their resumption tokens timed out. This fixes the calls to be more lazy,
so the initial OAI request for each call is delayed until those records are actually needed.
=> Make OAI multiset harvest truly lazy.

lib/krikri/parser.rb, spec/lib/krikri/mapper_spec.rb, spec/lib/krikri/parser_value_array_spec.rb
This allows you to call `#map` on DSL values to implement transforms.
=> Add `#map` to DSL Parser::ValueArray methods 

app/controllers/krikri/records_controller.rb, app/models/krikri/search_index_document.rb, spec/models/search_index_document_spec.rb
This fixes a bug in which items with dots in their ids create invalid routes.  Instead of using the full id uri, routes instead use local names.
=> use local names for item ids in routes

.gitignore, Gemfile, spec/spec_helper.rb
Here's a quick little addition for test coverage.
I added this quickly and it seems to work well enough; gives html reports in `./coverage`
It shouldn't run in ci tests.
=> Add test coverage with simplecov

app/controllers/krikri/activities_controller.rb, app/helpers/krikri/activities_helper.rb, app/models/krikri/activity.rb, app/views/krikri/activities/index.html.erb, config/routes.rb, krikri.gemspec, lib/krikri/prettifier_helper_behavior.rb, lib/krikri/search_results_helper_behavior.rb, spec/controllers/activities_controller_spec.rb
This was a self-serving thing I built out to make it easier for me to find and inspect instances of `Krikri::Activity` as I wrote the SPARQL queries for QA.
This also moves two methods from `Krikri::SearchResultsHelperBehavior` into a new
module, `Krikri::PrettifierHelperBehavior`.
=> Add controller/view for Krikri::Activity; add PrettifierHelperBehavior

lib/krikri/enrichments/genre_filter.rb, spec/lib/krikri/enrichments/genre_filter_spec.rb, spec/lib/krikri/enrichments/remove_empty_fields_spec.rb, spec/lib/krikri/enrichments/strip_html_spec.rb, spec/lib/krikri/enrichments/strip_punctuation_spec.rb, spec/lib/krikri/enrichments/strip_whitespace_spec.rb, spec/support/shared_examples/string_enrichment.rb
Removes values that do not match a given list of genre terms.
Also splits string enrichment shared examples to deal with string enrichments that don't want to ignore non-string values. The shared example which requires that is put into its own group so it can be combined as needed.
=> Add a genre filter enrichment

lib/krikri/enricher.rb, lib/krikri/enrichment.rb, lib/krikri/ldp/rdf_source.rb, lib/krikri/mapper.rb, lib/krikri/provenance_query_client.rb, spec/lib/krikri/enricher_spec.rb, spec/lib/krikri/job_spec.rb, spec/lib/krikri/mapper_agent_spec.rb, spec/support/shared_examples/rdf_source.rb
One Enricher run chains together multiple enrichments that get run on each record that was generated by a mapping activity.  The enrichments are specified in the options hash that is passed to `Enricher.enqueue`.
=> Add Enricher, a SoftwareAgent that runs enrichments

spec/lib/krikri/enricher_spec.rb
This method wasn't being covered by unit tests because the only
Enrichments that we have to date are FieldEnrichments.  A new Enrichment
class is mocked-up for the time being.
=> Add a test that covers Enricher#do_basic_enrichment

lib/tasks/krikri.rake
The arguments for `#add` changed, but this client did not. This fixes that.
I've created a chore for testing our rake tasks to prevent future regressions: https://www.pivotaltracker.com/story/show/91625412
=> Fixes rake sample record

solr_conf/schema.xml, spec/lib/krikri/search_index_spec.rb
This allows the solr schema to support documents with multiple rdf nodes for a given property (i.e. multiple creators, places, etc...).
The test checks `provider` particularly. We could improve it across the board by adding more data to DPLA::MAP::Aggregation's factory.
=> Support multivalued node fields in solr index

lib/krikri/job.rb, lib/krikri/software_agent.rb, spec/lib/krikri/job_spec.rb, spec/support/shared_examples/software_agent.rb
Despite `Krikri::Indexer` using `Krikri::EntityConsumer` to identify the activity for which to index records, `Krikri::Indexer#run` still needs an `activity_uri` parameter to meet the expectations of the interface
for `Krikri::Job#self.run`.
=> Allow Krikri::Indexer#run to receive an (unused) activity_uri

app/helpers/krikri/application_helper.rb, app/models/krikri/provider.rb, app/views/krikri/providers/index.html.erb, spec/helpers/krikri/application_helper_spec.rb, spec/models/provider_spec.rb
`Krikri::Provider#reload` builds out the triples associated with the provider through a SPARQL query. When there are more than a small number (say, 100) of mapped records in your repository, it takes
a very long time for it to build out the provider given that `#reload` calls `set_value` multiple times: one for each of the sum of the number of solutions for each mapped record associated with that provider.
=> Krikri::Provider#reload query should use a DISTINCT clause

app/controllers/krikri/validation_reports_controller.rb, app/views/krikri/validation_reports/_validation_report.html.erb, spec/controllers/validation_reports_controller_spec.rb
1. Iterate through each field returned in validation reports, now that title and isShownAt are multivalued in Solr
1. Link to compare view using `local_name(doc.id)`
1. Pass `@current_provider` as to the validation report view
=> Fixup validation report views

app/controllers/krikri/reports_controller.rb, app/controllers/krikri/validation_reports_controller.rb, app/models/krikri/validation_report.rb, spec/controllers/reports_controller_spec.rb, spec/controllers/validation_reports_controller_spec.rb, spec/models/validation_report_spec.rb, spec/support/shared_contexts/indexed_item.rb
This slightly reworks the `ValidationReports` model, and updates its consumers--adding tests for the functionality along the way.
There are a few places where integration testing/extensive mocking are called out.  These suggest a need for a more extensive rewrite of `ValidationReports` and/or a `ValidationReportBuilder` pattern to free those modules from that internal knowledge.  In the meanwhile, I think this makes everything work. :)
=> Rewrite validation reports model/controller; add tests

app/models/krikri/validation_report.rb
This fixes an issue where all items are identified as not having a `dataProvider`.
=> Update dataProvider field in validation report

lib/krikri/harvesters/couchdb_harvester.rb, spec/lib/krikri/harvesters/couchdb_harvester_spec.rb
Have `CouchdbHarvester` issue requests to CouchDB in paginated fashion, instead of using a stream.  Removes reliance by `#records` upon `Analysand::StreamingViewResponse`, which was having problems with certain UTF-8 characters.
Fix `CouchdbHarvester#record`, `#record_ids`, and `#count` methods to  exclude CouchDB design documents.
=> Have CouchdbHarvester make batch requests

app/controllers/krikri/records_controller.rb
`Krikri::RecordsController` was using different Solr field names to pull back facets and the fields to display in the index view. This changes them to use the proper fields.
=> Fix RecordsController to use correct Solr field names

lib/krikri/enrichments/split_coordinates.rb, spec/lib/krikri/enrichments/split_coordinates_spec.rb
Split strings given in edm:Place (`DPLA::MAP::Place`) into latitude and longitude.
=> Split geographic coordinate strings

lib/krikri/enrichments/move_non_dcmi_type.rb, spec/lib/krikri/enrichments/move_non_dcmi_type_spec.rb
Copies non-DCMI Type values to a new field via a 'generic' enrichment. This allows, e.g. moving values from `dctype` to `dcformat` before clearing the invalid values from `dctype`.
=> Adds an enrichment to copy non-DCMI type values

lib/krikri/enrichments/convert_to_sentence_case.rb, spec/lib/krikri/enrichments/convert_to_sentence_case_spec.rb
Converts a string to sentence case, removing capital letters in the sentences.
=> Add `ConvertToSentenceCase` enrichment

lib/krikri/parser.rb, spec/lib/krikri/parser_value_array_spec.rb
This behaves similarly to `#first_value`, in that it avoids overriding `#first` on the underlying (delegated) `Array`, but gives access to a `ParserValueArray` with only the requested values`.
=> Adds a `#last_value` to `ParserValueArray`

krikri.gemspec, lib/krikri/engine.rb, lib/krikri/enrichments/dcmi_enforcer.rb, lib/krikri/enrichments/dcmi_type_map.rb, spec/lib/krikri/enrichments/dcmi_enforcer_spec.rb, spec/lib/krikri/enrichments/dcmi_type_map_spec.rb
Adds two enrichments:
- A DCMI Type mapper, using a hash map and White Similarity to match strings to DCMI Types; and
- A DCMI Type enforcer to unceremoniously destroy any non DCMI values, or invalid URIs.
=> DCMI Type Enrichments

lib/krikri/enricher.rb, spec/lib/krikri/enricher_spec.rb
Creates a cache of enrichment objects for the current instance of `Krikri::Enricher`. This allows individual enrichment instances to maintain their own caches/persistence/optimizations for the life of (e.g.) a queued job.
=> Add Enrichment instance caching to Enricher

lib/krikri/map_crosswalk.rb
`edm:object` was used in MAPv3.x to mean `edm:preview`. That's fixed in 4.0; this fixes it in the mapping.
=> Update Crosswalk mapping for preview/object change

app/views/krikri/records/show.html.erb
This removes the scrolling feature for individual records on the side-by-side record comparison.
=> remove scroll from side-by-side records

app/controllers/krikri/records_controller.rb, solr_conf/schema.xml, solr_conf/solrconfig.xml
This adds 'Creator', 'Subject', and 'Collection' to the index fields for a record on the search results page.  It also reorders the fields.  It changes the source field for 'Type' from `sourceResource.type.id` to `sourceResource.type.name`. 
To test locally, generate a test app and start jetty.  You may need to stop, clean, and config jetty first:
`bundle exec rake jetty:stop`
`bundle exec rake jetty:clean`
`bundle exec rake jetty:config`
`bundle exec rake jetty:start`
Index a sample record with a value for `sourceResource.type.name`.  In your rails console:
`include FactoryGirl::Syntax::Methods`
`require 'dpla/map/factories'`
`agg = build(:aggregation)`
`agg.mint_id!('krikri_sample')`
`indexer = Krikri::QASearchIndex.new`
`graph = agg.to_jsonld['@graph'].first` …
=> Change index fields for records

lib/krikri/parser.rb, lib/krikri/parsers/json_parser.rb, lib/krikri/parsers/xml_parser.rb, spec/lib/krikri/parsers/json_parser_spec.rb, spec/lib/krikri/parsers/xml_parser_spec.rb
Add the ability to interpret boolean "or" expressions in the names passed to `Krikri::XmlParser#get_child_nodes` and `Krikri::JsonParser#get_child_nodes`, by way of `Krikri::Parser::ValueArray#field` and `#fields`.
This is necessary so that we can do the following sort of thing in our mappings:
```
providedLabel record.field('description', 'item|itemAv|fileUnit',
'physicalOccurrenceArray',
'itemPhysicalOccurrence|' \
'itemAvPhysicalOccurrence|' \
'fileUnitPhysicalOccurrence',
'referenceUnitArray', 'referenceUnit',
'name')
```
Both `XmlParser` and `JsonParser` have been modified so that usage is consistent between the two.
=> Add boolean or expressions to Krikri::Parser::Value subclasses

lib/krikri/enrichments/language_to_lexvo.rb, spec/lib/krikri/enrichments/language_to_lexvo_spec.rb, spec/support/matchers/active_triple_matchers.rb
Allows matching on Lexvo ISO 639-3 URIs. Matches string values and blank nodes with `providedLabel` properties. For the first match against an exact ISO code (or a label, e.g. 'english' if no code matches', produces a new blank node with `providedLabel` set to the input value and a `skos:exactMatch` link to the Lexvo URI.
=> Add ISO enrichment

lib/krikri/search_index.rb, spec/lib/krikri/search_index_spec.rb
Have the `QASearchIndex` constructor preserve default configuration
properties that are not being passed in via the `opts` argument to
`#initialize`.
This allows the Solr URI in Krikri::Settings.solr to be passed to
`RSolr.connect`.
Fixes https://www.pivotaltracker.com/story/show/91822774
=> Do not obliterate defaults, QASearchIndex constructor

krikri.gemspec, lib/krikri/enrichments/language_to_lexvo.rb, lib/krikri/enrichments/split_provided_label_at_delimiter.rb
This addresses the following issues:
* The order of the last few merges ended up breaking the build (when we merged the Audumbla abstraction before merging the language-to-Lexvo enrichment).
* Since the last release of Krikri/Heidrun, RSpec 3.3 was released, and running the specs under it breaks the build. I'm not sure why but I think that will have to wait for @no-reply to look at, because I'm guessing it's an issue with `rdf-spec` or `active_triples`. 
* This also addresses the `undefined method 'type' for .focus:Sass::Selector::Class (NoMethodError)` failure when precompiling the assets or running the specs for the `HarvestSourcesController`. `bootstrap-sass` introduced a small regression related to dependency resolution in version 3.3.5. The best nett step would be to upgrade Krikri …
=> Fix broken builds from enrichment merges and dependency resolution issues 

lib/krikri/mapper.rb, lib/krikri/parsers/xml_parser.rb, spec/lib/krikri/mapper_agent_spec.rb, spec/lib/krikri/parsers/xml_parser_spec.rb
If a non-existent path is given as the root node for a record, parsing failed with `NoMethodError` on an `#xml?` call to `nil`. This makes the parser throw a sensible error instead.
This should take care of error handling for the current ESDN mapping. It's an incremental improvement on error handling in mapping in general.
While we're in here, I'm open to suggestions about what to output as error context when `rec` is `nil`. `e.message` and `e.backtrace` may be enough.
=> Handle empty/non-existent root nodes on XmlParser

lib/krikri/search_index.rb, spec/lib/krikri/search_index_spec.rb
The QA index perviously required a manual commit following indexing jobs. `#update_from_activity` continues to return the same, but calls `solr#commit` after running its bulk adds.
=> Adds solr commit to solr bulk add processes

lib/krikri/enrichments/create_pref_label_from_provided.rb, spec/lib/krikri/enrichments/create_pref_label_from_provided_spec.rb
For most providers, we want to copy providedLabels into prefLabel prior
to running enrichments which will alter the label. This keeps the
providedLabels as a true representation of the original data.
Fields are ignored and returned as-is if:
- they are not `ActiveTriples::Resource`
- they do not respond to `#providedLabel`
- they already have a `prefLabel`
- there are no 'providedLabel`s present
=> Add enrichment to create prefLabels from provided

lib/krikri/harvesters/oai_harvester.rb, spec/lib/krikri/harvesters/oai_harvester_spec.rb
Sets up the Faraday client that makes OAI requests to log requests; this makes it possible to spot retried requests.
=> Log requests on OAI Harvests

krikri.gemspec, lib/krikri/harvesters/oai_harvester.rb, spec/lib/krikri/harvesters/oai_harvester_spec.rb
Rather than building a new XML document from scratch, it's now possible to use the REXML Element in the returned `OAI::Record` directly. This is the case from `ruby-oai` 0.4.0 on.
=> Use Ruby OAI's new `#_source` method to access XML

lib/krikri/parser.rb, spec/lib/krikri/parser_value_array_spec.rb
Expands the functionality of `#match_attribute` to accept a block to match against and adds an inverse `#reject_attribute` that deals with some cases brought on by Tennessee's MODS.
=> Adds `#reject_attribute` to the DSL `ValueArray`

app/models/krikri/provider.rb, spec/models/provider_spec.rb
This fixes an error that was causing the QA interface to crash if it tried to call `Krikri::Provider.name` on an indexed provider that was missing a value for `provider_name`.
=> check for existence of provider_name

lib/krikri/search_results_helper_behavior.rb, spec/helpers/krikri/records_helper_spec.rb
Aggregations previously displayed with full context. This displays them with only the actual records.
=> Display only the `@graph` in JSON-LD displays

lib/krikri/enrichments/language_to_lexvo.rb, spec/lib/krikri/enrichments/language_to_lexvo_spec.rb
We prefer the last rdf:Label from [RDF::ISO_639_3](https://raw.githubusercontent.com/dpla/dpla_map/map-4.0/lib/rdf/iso_639_3.rb). I.e. "French" rather than "French language" and "Creole, French" rather than "French Creole".
=> Add prefLabels to languages

krikri.gemspec
Pin rails_config to version 0.4.0 to prevent the error
"NameError: uninitialized constant Settings."
https://rubygems.org/gems/rails_config/versions/0.99.0 says "Please
install the Config gem instead."
=> Pin rails_config to version 0.4.0

krikri.gemspec
This updates DPLA::MAP to deal with the language handling issue we saw with previous enrichhments.
=> Update DPLA::MAP dependency to -pre.11

lib/krikri/enrichments/strip_ending_punctuation.rb, spec/lib/krikri/enrichments/strip_ending_punctuation_spec.rb
The ending punctuation enrichment was missing long words that ended with '.' due to an error in the regexp that was intended to keep it from removing the trailing '.' on initials. This fixes that by changing `*` to `+`.
=> Corrects ending punctuation enrichment

app/controllers/krikri/field_value_reports_controller.rb, app/controllers/krikri/reports_controller.rb, app/models/krikri/active_model_base.rb, app/models/krikri/field_value_report.rb, app/models/krikri/provider.rb, app/views/krikri/field_value_reports/show.csv.erb, app/views/krikri/reports/_field_value_report_list.html.erb, app/views/krikri/reports/index.html.erb, config/routes.rb, spec/controllers/field_value_reports_controller_spec.rb, spec/controllers/reports_controller_spec.rb, spec/models/active_model_template_spec.rb, spec/models/field_value_report_spec.rb, spec/models/provider_spec.rb, spec/views/krikri/reports/index.html.erb_spec.rb
This introduces field value reports based on data that has been indexed into Solr.  The field value reports show all values for a given field in documents with a given provider.  It addresses the following tickets:
https://www.pivotaltracker.com/n/projects/1172184/stories/79608350
https://www.pivotaltracker.com/n/projects/1172184/stories/79330180
https://www.pivotaltracker.com/n/projects/1172184/stories/85081820
__CSV downloads__
This only offers the reports as CSV downloads - there is no web interface for the reports. Each row of the CSV table has three columns: the reporting field, the document `id`, and the document's `isShownAt_id` link.
If a document has a missing value for the reporting field, it will show up in the CSV table with `__MISSING__` as the field value.
If there are no …
=> field value report with csv download

lib/krikri/enrichments/remove_empty_fields.rb, spec/lib/krikri/enrichments/remove_empty_fields_spec.rb
A Regex error caused the enrichment to remove fields beginning with whitespace + a newline, even if there was other content present.
=> Fix whitespace bug in RemoveEmptyFields

app/models/krikri/field_value_report.rb, spec/models/field_value_report_spec.rb
This was introduced by trying to use the admittedly clearer key `:batch_size`.
=> Fix FieldValueReport error where nil can't be coerced into Fixnum (fixes #7883)

app/views/krikri/field_value_reports/show.csv.erb
Without this fix, CSV data generated by `Krikri::FieldValueReport` would produce output like the following:
```csv
id,isShownAt_id,sourceResource_rights
krikri_sample,http://digitalcollections.nypl.org/items/510d47e3-57d2-a3d9-e040-e00a18064a99,&quot;The New York Public Library is interested in learning more about items you&#39;ve seen on our websites or elsewhere online. If you have any more information about an item or its copyright status, we want to hear from you. Please contact DigitalCollections@nypl.org with your contact information and a link to the relevant content.&quot;
```
=> Fix issue with unnecessarily escaped HTML entities in CSV reports

krikri.gemspec, lib/krikri/engine.rb, lib/krikri/enrichments/dcmi_enforcer.rb, lib/krikri/enrichments/language_to_lexvo.rb
This upgrades to DPLA::MAP pre.12. It removes the dependency on LinkedVocabs, which is deserving of a rewrite against the latest `ActiveTriples` work and updated BNode handling.
=> Upgrade DPLA::MAP

app/models/krikri/activity.rb, lib/krikri/provenance_query_client.rb, spec/models/activity_spec.rb
Punts `#to_s` to `#inspect` to simplify activity discovery, e.g.:
puts Krikri::Activities.all
This was bothering me, now it shouldn't anymore.
=> Add `Activity#to_s` for easier activity display

lib/krikri/map_crosswalk.rb, spec/lib/krikri/map_crosswalk_spec.rb
Fixes a typo on `prefLabel` which caused failure on index for certain records.
Adds a regression test.
=> Fix prefLabel issue in map_crosswalk

app/models/krikri/activity.rb, lib/krikri/enricher.rb, lib/krikri/harvester.rb, lib/krikri/indexer.rb, lib/krikri/logger.rb, lib/krikri/search_index.rb, lib/krikri/software_agent.rb, spec/lib/krikri/enricher_spec.rb, spec/lib/krikri/indexer_spec.rb, spec/lib/krikri/search_index_spec.rb, spec/models/activity_spec.rb, spec/support/shared_examples/software_agent.rb
Instead of catching everything at the top level Indexer, we now handle
errors within the index implementation. Anything that reaches the
Indexer is treated as an failure state and logged accordingly, then
reraised.
=> Handle errors in indexer

lib/krikri/map_crosswalk.rb, spec/lib/krikri/map_crosswalk_spec.rb
Maps language to a structure like:
{ name: 'English', iso639_3: 'eng' }
Also fixes a minor bug on subject terms, allowing us to index prefLabels
with preference over providedLabels.
=> Fix map crosswalk language

lib/krikri/enrichments/web_resource_uri.rb, spec/lib/krikri/enrichments/web_resource_uri_spec.rb
`edm:WebResource` nodes should __always__ be an HTTP URI. This removes them if a blank node is given.
=> Add enrichment to clear WebResource Blank Nodes

lib/krikri/search_index.rb, spec/lib/krikri/search_index_spec.rb
Passing in an empty options hash overwrote the default options, so jobs
would never use the defaults. This merges the options.
A side effect is that we avoid calling `#delete` on the original options
hash, leaving it intact for the caller.
=> Merge index options with defaults

lib/krikri.rb, spec/support/shared_examples/rdf_source.rb
This commit should be reverted when https://github.com/gkellogg/ebnf/issues/5 is suitably closed.
=> Monkeypatch parser Scanner to catch long terminals

lib/krikri/mapper.rb, lib/krikri/mapping.rb, spec/lib/krikri/mapper_spec.rb, spec/lib/krikri/mapping_spec.rb
Introduces a `Mapping::Error` that tracks multiple errors for a given
record and handles messaging.
In the `Mapping`, we catch errors for each declaration on a given
record, storing them with the relevant property name, and re-raise. The
`Mapper` then simply catches the error and logs its message.
This simplifies handling outside the DSL code, and creates richer error
messages.
=> Error handling in Mapping

Gemfile, krikri.gemspec
RDF 1.99.0 was released recently and introduces many deprecation warnings in preparation for the RDF 2.0 release coming around the turn of the calendar year. We expect 1.99.1, and perhaps some other minor releases between now and then. 1.99.1 will contain most or all of the features that make it into 2.0.
This locks us to `1.1.x` until we can make a deliberate upgrade. My suggestion would be to wait for that until *at least* 1.99.1, reducing the number and complexity of the upgrades.
=> Pin to RDF 1.1.x

lib/krikri/ldp/rdf_source.rb
`Net::HTTP` is returning `ASCII-8BIT` strings for some responses (see [this code](https://github.com/ruby/ruby/blob/trunk/lib/net/http/response.rb#L373-L377) and [this issue](https://bugs.ruby-lang.org/issues/2567)). This forces `RDFSource` responses (which for LDP MUST be `text/turtle` and therefore UTF-8, if requested) to read as UTF-8.
We considered using middleware like [`Faraday::Encoding`](https://github.com/ma2gedev/faraday-encoding) but Marmotta does not return an explict encoding in `content-type` headers.
=> Force encoding on RDFSource response bodies

lib/krikri/harvesters/oai_harvester.rb, spec/lib/krikri/harvesters/oai_harvester_spec.rb
Adds error recovery when an attempt to retrieve a set throws an
`OAI::Excepton`. OAI-PMH requests throw errors when no matches can be
found with (e.g.) the required metadata prefix. When this happens we
want to pass over the set, logging & returning empty, instead of
aborting the harvest.
Note that the failover applies to *any* OAI exception. We've observed
that some provider endpoints report different errors, and
`OAI::Exception` does little to help us identify error types. This may
turn out to be heavy-handed.
=> Allow OAI to recover on errors when iterating sets

lib/krikri/parser.rb
This is used for error reporting by Mapping::Error when a mapping error
occurs inside a ChildDeclaration block.
Without this, errors would throw:
```
NoMethodError: undefined method `local_name' for #<Krikri::PrimoParser:0x007fa42ec51500>
```
=> Expose local_name through the Parser interface

lib/krikri/map_crosswalk.rb, spec/lib/krikri/map_crosswalk_spec.rb
The 3.1 crosswalk mistakenly mapped arrays of lats & long into a string, resulting in coordinates like `"[\"12.34\"], [\"56.78\"]"`. This patch grabs the first value of each, resulting in the correct value.
=> Fix coordinates for MAP 3.1 JSON Crosswalk

app/models/krikri/original_record.rb, lib/krikri/ldp.rb, lib/krikri/ldp/invalidatable.rb, lib/krikri/ldp/rdf_source.rb, lib/krikri/ldp/resource.rb, spec/models/original_record_spec.rb, spec/support/shared_examples/ldp_invalidatable.rb, spec/support/shared_examples/rdf_source.rb
Uses prov:invalidatedAtTime to mark resources as invalidated (soft
deleted). This is different from `#delete!` which sends an HTTP/LDP
DELETE request, permanently marking the resource as `410 Gone`.
We aim to invalidate, usually, rather than delete.
Implemented as a mixin that works with objects implementing an
`#rdf_source` method returning a `Krikri::LDP::RDFSource`.
=> Add #invalidate! for LDP resources

krikri.gemspec, lib/krikri/map_crosswalk.rb, spec/lib/krikri/map_crosswalk_spec.rb
* Ensure an `edm:TimeSpan`'s `skos:prefLabel` is being mapped to the `:displayDate` key.
* Make `dct:temporal` crosswalked to MAPv3.1 JSON-LD using the `Krikri::MapCrosswalk::CrosswalkHashbuilder#build_time_span` method.
* Add a spec to ensure that improperly typed `dc:date`/`dct:temporal` values do not get mapped to MAPv3.1 JSON-LD based on the expectations of the index.
=> Ensure MAPv4 to 3.1 crosswalk date/temporal consistency (fixes #8228)

lib/krikri/engine.rb, spec/lib/krikri/search_index_spec.rb, spec/models/dpla/map/aggregation_spec.rb, spec/support/shared_contexts/entities_query.rb
This reorders the spec to used the :opts passed by RSpec to be only used in the context describing `#initialize`, and removes the mock that was preventing the appropriate method from firing. It also modifies the `entities query` shared context to set subject URI for the built aggregations.
The specs that test Krikri::ProdSearchIndex with an Elasticsearch connection were being skipped in Travis, and they failed for me locally. It looked in some cases as though it was trying to make a connection to http://example.org/moomin-index/moomin as used in the describe block.
=> Fix failing ProdSearchIndex spec that was skipped in CI

lib/krikri/async_uri_getter.rb, spec/lib/krikri/async_uri_getter_spec.rb
Replaces #208. See discussion there.
4e272bd is the only commit changed from the previous discussion. It contains some YARD annotation updates, minor style changes, and **one substantial change**:
- `#http` is cached within the `Request` instance. This should make no difference now (the connection and instance would have garbage collected at the same time anyway), but will prevent spawning multiple `Faraday` connections per `Request` if for some reason `Resquest` changes in the future. https://github.com/dpla/KriKri/compare/asynchronous-harvesters?expand=1#diff-a93afa836b08961677e7a6870c08c992R106
@anarchivist and/or @markbreedlove should sanity check that before merging.
=> Asynchronous harvesters

app/models/krikri/original_record.rb, lib/krikri/engine.rb, spec/krikri_spec.rb
By default, `RDF::URI::CACHE_SIZE` is `-1` and all URIs initialized with
`RDF::URI.intern` are cached for the life of the application. In job
scenarios, this leads to a slow growth of the cache, as more unique URIs
are added. For a good number of the URIs we're using (e.g. LDP URIs and
their `#sourceResource` fragments), use is scoped to the processing of
one record. Limiting the cache size allows these to cycle out, while
commonly used URIs should stay in the cache avoiding duplicate objects
in memory.
The cache size is given by `Krikri::Settings['uri_cache_size']`, and
defaults to `1_000_000` (cached URIs). We could choose to change the
cache size on various worker boxes by installing unique settings
values.
Setting the cache size at application startup causes a warning to be
thrown …
=> Limit `RDF::URI.cache` capacity

lib/krikri/harvester.rb, lib/krikri/harvesters/oai_harvester.rb, spec/lib/krikri/harvesters/oai_harvester_spec.rb
By default, we use the `identifier` field of the OAI header to seed the
record id minter. In the legacy system, the ids used were derived from
the `dc:identifier` field in `metadata`.
This patch allows harvesters for those sources to select a field with an
xpath expression, passed as `[:oai][:id_path]` in options.
=> Allow OAI harvesters to use alternate ID sources

app/models/krikri/activity.rb, lib/krikri/entity_behavior.rb, lib/krikri/entity_behaviors/aggregation_entity_behavior.rb, lib/krikri/entity_behaviors/original_record_entity_behavior.rb, lib/krikri/provenance_query_client.rb, spec/lib/krikri/aggregation_entity_behavior_spec.rb, spec/lib/krikri/original_record_entity_behavior_spec.rb, spec/lib/krikri/provenance_query_client_spec.rb, spec/models/activity_spec.rb, spec/support/shared_contexts/provenance_query_client.rb
By default, filter aggregations from `Krikri::Activity#entity_uris` and `#entities` that have been invalidated -- i.e. soft-deleted.
See https://www.w3.org/TR/prov-o/#invalidatedAtTime
See https://github.com/dpla/KriKri/commit/aab20d906e67f23aa5728bec3c6048e081dfd016
The most significant change is to `Krikri::ProvenanceQueryClient`, which is responsible for the SPARQL query that either includes or excludes invalidated aggregations.
Addresses https://issues.dp.la/issues/8237
If there's any concern about making the SPARQL query more complex and having that negatively impact query speed, I've benchmarked the old and new queries; and the new one, without invalidated records, appears to complete faster.  I've benchmarked these by restarting PostgreSQL and Marmotta in between, and by rebooting …
=> Filter invalid records from `#entities` and `#entity_ids`

app/models/krikri/original_record.rb, krikri.gemspec, lib/krikri/engine.rb, lib/krikri/map_crosswalk.rb, spec/ldp/resource_spec.rb, spec/lib/krikri/harvesters/oai_harvester_spec.rb, spec/lib/krikri/map_crosswalk_spec.rb, spec/lib/krikri/mapping_dsl/parser_methods_spec.rb, spec/lib/krikri/mapping_dsl/rdf_subjects_spec.rb, spec/models/activity_spec.rb, spec/models/dpla/map/aggregation_spec.rb, spec/models/original_record_spec.rb, spec/support/matchers/active_triple_matchers.rb
RSpec is nearing a 3.5 release, which will be necessary for Rails 5 compatibility. This gets us closer to that.
It also fixes up warnings raised by newer versions of RSpec.
The dependency is loosened so engine users aren't forced to upgrade.
=> Allow use of RSpec 3.4.x

lib/krikri/harvesters/oai_harvester.rb
The OAIHarvester previously gave `true` in `#records` when an error was caught building the record. `#run` handles `nil`, so we should return that instead.
Logging an error returns `true`, so code like this:
```ruby
map do |r|
begin
some_logic(r)
rescue => e
log(e)
end
end
```
...results in `true` in the mapped enum. Calling `next` gives `nil` as required.
This fixes an issue originally identified here: https://dpla.slack.com/archives/tech/p1456162536000069
=> Call `next` when logging errors in `#record`

config/settings/development.yml, config/settings/test.yml, lib/krikri/engine.rb, spec/krikri_spec.rb
Add a `read_timeout` parameter that governs how long our SPARQL client will wait for Marmotta to respond to HTTP requests.
This is useful for avoiding timeouts of provenance queries.
=> Add configurable Marmotta read timeout

lib/krikri/harvester.rb, spec/lib/krikri/harvester_spec.rb
Move the definition of `Krikri::Harvester.entity_behavior` to the `included` block, because `Harvester` is a mixin.
Add a test to ensure that a class mixing in Harvester receives `Krikri::OriginalRecordEntityBehavior` from a call to `.entity_behavior`.
=> Fix definition of Krikri::Harvester.entity_behavior

app/models/krikri/activity.rb, lib/krikri/enricher.rb, lib/krikri/entity_behavior.rb, lib/krikri/entity_behaviors/aggregation_entity_behavior.rb, lib/krikri/entity_behaviors/original_record_entity_behavior.rb, lib/krikri/entity_consumer.rb, lib/krikri/indexer.rb, lib/krikri/mapper.rb, lib/krikri/search_index.rb, lib/krikri/software_agent.rb, spec/lib/krikri/entity_consumer_spec.rb, spec/lib/krikri/harvester_spec.rb, spec/lib/krikri/indexer_spec.rb, spec/lib/krikri/mapper_agent_spec.rb, spec/models/activity_spec.rb, spec/support/shared_examples/software_agent.rb
Refactors `EntityConsumer` to respond to `#entities` and to accept a generalized entity_source.  For the moment, it retains the previous generator activity behavior as a deprecated interface, to continue to serve the index classes, which are tightly coupled to `Activity`. `Mapper::Agent` and `Enricher` are refactored to use the new interface.
Moves activity URI lookup to `Activity` & exposes more public interfaces for working with activity URIs; Refactors `EntityConsumer` to rely on this logic, instead of using a coarse string based matcher.
Tests and docs are fixed up throughout.
=> Entity Consumer Refactor/Deprecation

spec/lib/krikri/harvester_spec.rb
In Harvester spec, fix ".entity_behavior knows its entity_behavior" to expect `subject.entity_behavior` instead of `klass.entity_behavior`.
That should normally fail, because `klass` should not be expected to have `include`d `Krikri::Harvester` yet.  Depending on the order in which the specs were run, the issue was being masked, because the spec was operating on a `klass` that had had `Harvester` included by an earlier spec.
=> Fix harvester_spec.rb test with wrong expect subject

spec/lib/krikri/indexer_spec.rb, spec/lib/krikri/search_index_spec.rb, spec/models/provider_spec.rb, spec/spec_helper.rb, spec/support/shared_contexts/indexed_item.rb
The particular issue was in the specs for
`Krikri::QASearchIndex#update_from_activity`. These got left behind,
some tests had apparently compensated for this by cleaning up in
`before`. That behavior is removed, to make it easier to catch issues
like this in the future.
Also normalizes solr index cleanup on the `clear_search_index` helper. I
think this was added after some of these specs were written, and some of
them never got migrated.
=> Remove Solr docs more carefully in test suite

lib/krikri/async_uri_getter.rb, spec/lib/krikri/async_uri_getter_spec.rb
If this option is set to true, connection-level errors (like
CONNREFUSED, socket timeouts, etc.) will be delivered to the
caller as HTTP 5xx responses.
-----
The context to this is https://github.com/dpla/heidrun/pull/38, where for the IA harvester we want to ignore connection refused/timeout exceptions and just skip over the affected records.
The IA harvester already skips records when it gets back a 5xx error response, so we really just want it to do the same thing for exceptions caused by connection errors.  It seemed a shame to complicate the harvester code with a bunch of exception handling--especially when future harvesters will likely want the same thing--so I added the option for "inline exceptions" to give the caller the option of handling all types of errors in a uniform way. …
=> Add support for "inline exceptions"

lib/krikri/async_uri_getter.rb, spec/lib/krikri/async_uri_getter_spec.rb
Previously an exception thrown in the body of a `with_request` block
would be caught and propagated as an inline exception.  This can be
quite confusing when your `with_request` block is suddenly being called
twice!
Added a test to catch this case too.
-----
Only too late do I realize I should have called this branch "inline-exception-inception".  Damn.
=> Only inline exceptions stemming from Faraday

lib/krikri/util/extended_date_parser.rb, spec/lib/krikri/util/extended_date_parser_spec.rb
Intervals do not have their own precision, but instead rely on the precision of their begin and end date/time. This fixes a `NoMethodError` on `EDTF::Interval#uncertain!` and adds coarse handling for interval uncertainty.
=> Handle EDTF Intervals

lib/krikri/enrichments/split_on_provided_label.rb, spec/lib/krikri/enrichments/split_on_provided_label_spec.rb
Splits a resource into multiple resources when multiple providedLabel are present.
This is useful when a mapping error or limitation in partner data makes it impossible/impractical to split resources properly at mapping time. This is the case with NARA's subject mapping (it's not clear yet whether "impossible/impractical" is the case--this may simply be our mistake).
=> Add SplitOnProvidedLabel enrichment

lib/krikri/enrichments/language_to_lexvo.rb, spec/lib/krikri/enrichments/language_to_lexvo_spec.rb
`LanguageToLexvo` now matches three-letter language codes independent of case.
=> Make language code matching case insensitive

Gemfile
Guard has stopped supporting Ruby 2.1. I'm removing the dependency, pending an upgrade on our end.
See:
https://github.com/guard/guard#important-ruby-21-is-officially-outdated-and-unsupported-please-upgrade-to-ruby-23-or-225-before-installing-guard
=> Remove guard dependency

lib/krikri/parser.rb, spec/lib/krikri/parser_value_array_spec.rb
Allows index and range access on `Krikri::Parser::ValueArray` objects, maintaining method chaining.
=> Add array index access; mimics `Array#at`

lib/krikri/parser.rb, spec/lib/krikri/parser_value_array_spec.rb
Makes it possible to squash out `nil` values in value array with `#compact`.
=> Add `#compact` to mapping DSL

lib/krikri/mapping_dsl/child_declaration.rb, lib/krikri/mapping_dsl/property_declaration.rb, spec/lib/krikri/mapper_spec.rb, spec/lib/krikri/mapping_dsl/child_declaration_spec.rb
MappingDSL Declarations were somewhat messy and under-documented, particularly the `#to_proc` methods. This refactors slightly, removing some undue complexity. It also documents the Declaration classes much more thoroughly.
The second commit satisfies rubocop about the related integration tests in `mapper_spec.rb`.
=> Refactor & Document MappingDSL #to_procs

krikri.gemspec
Nokogiri had security vulnerabilities in versions `>= 1.6.0`, `< 1.6.8`. Since Blacklight requires `~> 1.6`, it seems good to force engine users to use `1.6.8` or greater.
Our production instance upgraded in a deployment some time ago.
=> Force Nokogiri security upgrade

lib/krikri/map_crosswalk.rb, spec/lib/krikri/map_crosswalk_spec.rb
TimeSpan mappings in the DPLA MAP v3.1 crosswalk need to map labels aggressively. If no label is given, the frontend won't display a date. This maps `prefLabel` with preference, but uses `providedLabel` as a backup.
Closes https://issues.dp.la/issues/8457.
=> Map providedLabel in TimeSpan

lib/krikri/enrichments/timespan_label.rb, spec/lib/krikri/enrichments/timespan_label_spec.rb
The new enrichment sets a `prefLabel` based on existing begin/end dates
within a TimeSpan.
Does nothing if:
- a `prefLabel` is already present
- neither a begin, nor end date is given
=> Add TimespanLabel enrichment

lib/krikri/map_crosswalk.rb, spec/lib/krikri/map_crosswalk_spec.rb
* Map providedLabel first and then label only if no providedLabel exists. 
* Fixup the spec test for map_crosswalk
* Misc. whitespace cleanup
=> Fixup build_place 

lib/krikri/map_crosswalk.rb, spec/lib/krikri/map_crosswalk_spec.rb
Use providedLabel with preference, falling back on prefLabel if needed.
=> Use providedLabel in TimeSpan for MAP 3.1

lib/krikri/parser.rb, spec/lib/krikri/parser_value_array_spec.rb
Introduces a syntax for matching or rejecting nodes based on the
presence of a child node.
For instance:
record.field('mods:subject').reject_child('mods:hierarchicalGeographic')
Closes https://issues.dp.la/issues/8207
=> Mapping DSL match/reject based on child node.

spec/lib/krikri/async_uri_getter_spec.rb
The `raise_error` matcher wants to check against a real error message to
avoid false positives. In addition to giving it a parameter, I needed to
fix a false positive (via WebMock) to make this test pass.
=> Fix RSpec warning on `raise_error`

krikri.gemspec
Upgrades the `edtf` gem and locks to the most recent major version.
The new version was released over the weekend.
=> Upgrade EDTF to 3.0

app/controllers/krikri/records_controller.rb
For all existing facets in the QA interface that have both `prefLabel` and `providedLabel`, this makes facets for both.  One exception is `language`, which has a `providedLabel` but no `prefLabel` in the solr schema.
For most fields, `name` in the solr schema corresponds with `prefLabel`, so `sourceResource_type_name` is the `prefLabel` for `type`.  The one exception seems to be `collection`, for which `title` corresponds to `prefLabel`.
There are no tests b/c this uses Blacklight functionality.  There are currently no tests in `Krikri` for faceting behavior.  This has been tested locally using sample data.  It addresses [ticket #8501](https://issues.dp.la/issues/8501).
=> facets for pref and provided labels

app/models/krikri/field_value_report.rb, spec/models/field_value_report_spec.rb
This adds more fields for generating field value reports.
It also corrects the key name for `sourceResource_alternative`.
This has been tested locally.  It addresses [ticket #8205](https://issues.dp.la/issues/8502).
=> add more field value reports

lib/krikri/mapper.rb
There's no need to lookup the mapping in the registry for each record. Just look it up once and hold the mapping in memory.
This is a minor optimization, but it was easy and might make a difference in GC.
=> Avoid calling `Registry#get` repeatedly

solr_conf/schema.xml
This removes fields from the solr schema that are not needed for QA, nor for features/functionality elsewhere in the Krikri application.  These fields will no longer be indexed.
This addresses [ticket #8523](https://issues.dp.la/issues/8523).
=> remove un-needed fields from solr schema

app/controllers/krikri/records_controller.rb
This changes the character that delimits terms appearing in search results from a comma to a semicolon.
This has been tested locally.  I did not write an rspec test b/c this is a utilization of existing Blacklight behavior.
This addresses [ticket #8506](https://issues.dp.la/issues/8506).
=> delimit index fields with ;

.travis.yml
Allow failure for ruby 2.3.0.  This is a prerequisite for adding the blacklight-gallery gem with our current dependencies.  See https://github.com/dpla/KriKri/pull/263
=> allow failure for ruby 2.3.0

app/controllers/krikri/records_controller.rb, krikri.gemspec, lib/generators/krikri/install_generator.rb, lib/krikri.rb
This adds a gallery view for search results, using the blacklight-gallery gem.
Since we are still using blacklight 5, the most recent version of blacklight-gallery we can use is 0.3.0.  Unfortunately, blacklight-gallery 0.3.0 fails with ruby 2.3.0, so we have to allow failure for ruby 2.3.0 until we can upgrade our dependencies.  [Ticket 8534](https://issues.dp.la/issues/8534) addresses this issue.
As requested by GG, the gallery view only shows the image - no additional metadata is displayed.
This has been tested locally.  It addresses [ticket #8504](https://issues.dp.la/issues/8504).
=> add gallery view for search results

lib/krikri/mapping_dsl/child_declaration.rb, spec/lib/krikri/mapper_spec.rb, spec/lib/krikri/mapping_dsl/child_declaration_spec.rb
"Variables" declared as scoped DSL methods were mistakenly cast to their
`#value` when we want a `ValueArray`. This restores the old behavior and
adds an integration test.
This could still use a significant refactor. There is probably a way to
do this without nested iterations through the values. Additionally,
`RecordProxy#dup` is customized in a way that makes this somewhat
tightly coupled and hard to read.
Fixes https://issues.dp.la/issues/8522.
=> Restores `ValueArray` in scoped DSL variables

lib/krikri/parser.rb, spec/lib/krikri/mapper_spec.rb, spec/lib/krikri/parser_value_array_spec.rb
The new `#field_names` method returns a value array with the available field names (labels of child nodes) for the current node. This supports cases like `{'language' => { 'english' => 'some value', 'french' => 'some other value' }` with `.language.field_names` giving the keys.
=> DSL method for accessing field names

krikri.gemspec
Pin gems to tiny versions currently running in heidrun production.
This addresses (in part) [ticket #8538](https://issues.dp.la/issues/8538).
=> pin gems to minor versions

lib/krikri/enrichments/dcmi_type_map.rb
Addresses issue #4 in this ticket https://issues.dp.la/issues/8549#note-3
=> Add mapping for "online text" to DCMI map
