dpla/KriKri

Rakefile, lib/generators/krikri/install_generator.rb, lib/generators/krikri/templates/schema.xml, lib/generators/krikri/templates/solrconfig.xml, lib/tasks/jetty.rake, lib/tasks/krikri.rake
This allows a host application to run jetty rake tasks successfully.
=> Set Jettywrapper URL and Marmotta Home in host

.travis.yml, Gemfile, README.md, spec/spec_helper.rb
Assuming we want this, it should work.  Test coverage reporting isn't perfect (it will never tell you whether you're testing effectively), but it might help us spot problem areas.
http://blog.codeclimate.com/blog/2013/09/11/test-coverage-and-code-quality-better-together/
=> Add codeclimate test coverage reporting

lib/krikri/enrichments/strip_punctuation.rb, lib/krikri/enrichments/strip_whitespace.rb, spec/lib/krikri/enrichments/strip_punctuation_spec.rb, spec/lib/krikri/enrichments/strip_whitespace_spec.rb
This closes https://www.pivotaltracker.com/story/show/83402006
=> Add strip whitespace and punctuation enrichments

lib/krikri/enrichments/strip_html.rb, spec/lib/krikri/enrichments/remove_empty_fields_spec.rb, spec/lib/krikri/enrichments/strip_html_spec.rb, spec/lib/krikri/enrichments/strip_punctuation_spec.rb, spec/lib/krikri/enrichments/strip_whitespace_spec.rb, spec/support/shared_examples/string_enrichment.rb
Closes https://www.pivotaltracker.com/story/show/85082098
=> Add enrichment to strip HTML tags

Gemfile, krikri.gemspec, lib/krikri/engine.rb, lib/krikri/harvesters/couchdb_harvester.rb, spec/lib/krikri/harvesters/couchdb_harvester_spec.rb, spec/lib/krikri/harvesters/oai_harvester_spec.rb, spec/support/shared_examples/harvester.rb
This is now ready for review. Thanks to @no-reply for help on figuring out what was going on with the specs.
=> CouchDB Harvester

README.md, krikri.gemspec, lib/krikri/version.rb
=> Bump version to 0.1.0

lib/krikri/engine.rb, spec/models/dpla/map/aggregation_spec.rb
cc @no-reply - perhaps you can give this a sanity check, or help out on this branch?
=> Set fragment URI for first sourceResource on ore:Aggregations

lib/krikri/engine.rb, lib/krikri/index_service.rb, lib/tasks/krikri.rake, spec/krikri_spec.rb, spec/lib/krikri/index_service_spec.rb
This makes it possible to configure the `IndexService` to use a solr server other than `localhost`.
Testing this is hard because `IndexService` is effectively a singleton... thinking about a refactor.
=> Use solr settings in `IndexService`

lib/krikri/mapping_dsl/parser_methods.rb, spec/lib/krikri/mapper_spec.rb, spec/lib/krikri/mapping_dsl/parser_methods_spec.rb
Okay... integration testing... blah.
=> Rework `#header` parser method; add integration test

lib/krikri/engine.rb
This extends upon dpla/krikri#101, which did not fully fix the issue. It turns out
there is an underlying issue with ActiveTriples (see ActiveTriples/ActiveTriples#107).
This rebuilds the SourceResource and appropriately sets the subject to the required
fragment URI.
Do not merge until the tests are done.
=> Forceably update SourceResource instances on Aggregations

spec/lib/krikri/harvester_spec.rb
This is just a minor cleanup to improve the test coverage slightly.
=> Add tests for unimplemented methods in `Harvester`

db/migrate/20150310190054_remove_opts_limit_in_krikri_activities.rb
=> Remove limit from opts

lib/krikri/harvesters/oai_harvester.rb, spec/lib/krikri/harvesters/oai_harvester_spec.rb
Slightly improves testing for laziness of multi-set harvests. Adds some doc annotations to OAIHarvester methods.
These are just some minor improvements I made while diagnosing another issue.
=> Improve tests and documentation in OAIHarvester

lib/krikri/enrichments/timespan_split.rb, lib/krikri/util/extended_date_parser.rb, spec/lib/krikri/enrichments/timespan_split_spec.rb, spec/lib/krikri/util/extended_date_parser_spec.rb
The date parser now works with variations on 'circa' and some other random date formatting quirks.
=> Add support for additional date formats

lib/krikri/enrichments/limit_characters.rb, spec/lib/krikri/enrichments/limit_characters_spec.rb
This enrichment truncates strings that are more than 1000 characters.
=> enrichment limits string to 1000 characters

lib/krikri/enrichments/split_provided_label_at_delimiter.rb, spec/lib/krikri/enrichments/split_provided_label_at_delimiter_spec.rb
This is needed to split the UW subjects.
=> Add enrichment to split a resource by its providedLabel

lib/krikri/engine.rb, lib/krikri/map_crosswalk.rb, lib/krikri/search_index.rb, spec/lib/krikri/map_crosswalk_spec.rb
Adds a `CrosswalkHashBuilder` that constructs DPLA MAP 3.1 JSON-LD, with appropriate additions for indexing into our production ElasticSearch.
=> Format Aggregations to MAP 3.1 for indexing

app/assets/javascripts/krikri/application.js, app/controllers/krikri/records_controller.rb, config/routes.rb, solr_conf/solrconfig.xml
This is still in progress, but I'm opening a PR since I'll need some help with someone (maybe @AudreyAltman) on this - I'm having some JS issues that are preventing the modal from opening.
=> Add additional facets and change pagination

README.md
Add a little note with advice on when to use the included VM vs. when to use the VMs in `automation`.
=> Add VM usage note to README

lib/krikri/mapper.rb, lib/krikri/mapping.rb, lib/krikri/mapping_dsl.rb
Fixing some documentation while I'm in these files.
=> Update documentation for mapping related modules

lib/krikri/parser.rb, spec/lib/krikri/parser_value_array_spec.rb
For initial review:
```ruby
value_array.if { |arry| arry.field(:a_field) }
.else { |arry|  arry.field(:alternate_field) }
value_array.if.field(:a_field).reject { |v| v == 'SKIP ME' }
.else { |arry|  arry.field(:alternate_field) }
```
This addresses the use case in: https://github.com/dpla/heidrun-mappings/commit/5768026c078ab1a037d7eb043f4abd9b72a9f289#commitcomment-13144153
=> Add if/else for `Parser::ValueArray`

.travis.yml
Add previous stable, 2.0.0 stable, and current stable to Travis config.
=> Test support for Ruby versions

lib/krikri.rb, lib/krikri/harvesters/primo_harvester.rb, lib/krikri/parsers/primo_parser.rb, spec/factories/krikri_original_record.rb, spec/lib/krikri/harvesters/primo_harvester_spec.rb, spec/lib/krikri/parsers/primo_parser_spec.rb
The getty & MWDL mappings will depend on this.
=> Add a primo harvester

provisioning/files/install_ruby_tools.sh
Fixes the same issues as https://github.com/dpla/heidrun/pull/41
=> Fix install_ruby_tools.sh issues

lib/krikri/engine.rb, spec/models/dpla/map/aggregation_spec.rb
Raise an exception when minting an ID in `DPLA::MAP::Aggregation#mint_id!` if there is no original record, instead of generating a random one.
As previously written, if a mapping failed to map `originalRecord`, you would end up with two `RDFSource`s, one for the harvested record, and one for the mapped record with a random ID.
Also improve the existing error messaging for `DPLA::MAP::Aggregation#original_record` when there's no original record.
=> Raise error for empty original record, minting ID

krikri.gemspec
=> add scott as author

.gitignore, .travis.yml, Gemfile, README.md, krikri.gemspec
=> Update engine_cart to ~> 1.0.1 (fixes #8556, #8557)
